<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_ProfileDropdown</name>
   <tag></tag>
   <elementGuidId>8da3df49-44f8-4426-a2ca-e3cad8ff6d03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//cnv-dropdowns[@cnv-dropdown-ctrl='userMenuDropdownCtrl']//i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//cnv-dropdowns[@cnv-dropdown-ctrl='userMenuDropdownCtrl']//i</value>
   </webElementProperties>
</WebElementEntity>
