<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Smart_Notifications</name>
   <tag></tag>
   <elementGuidId>61d8b7ff-ed1a-421f-9535-a4942b20efb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//label[@for='noti_notify_only_when_away']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//label[@for='noti_notify_only_when_away']</value>
   </webElementProperties>
</WebElementEntity>
